### ISSUE TITLE
While compiling with g++ 8.2.0 std::ignore cannot be found

### ISSUE THREAD

**Issue by rhalver** [ECP-copa/Cajita#1]
Using g++ 8.2.0 to compile Cajita leads to an error, when std::ignore cannot be
resolved in src/Cajita_UniformDimPartitioner.cpp:

```
/home/halver/install/Cajita/src/Cajita_UniformDimPartitioner.cpp:21:10: error: ‘ignore’ is not a member of ‘std’
     std::ignore = global_cells_per_dim;
          ^~~~~~
```

**Comment by sslattery** [comment]
@rhalver I have pushed a fix. Please take a look when you get a chance to determine if it is sufficient. Thanks!

**Comment by rhalver** [comment]
It seems to be sufficient, the code now compiles.
