### ISSUE TITLE
Problem when using g++ with a Kokkos version compiled with CUDA

### ISSUE THREAD

**Issue by rhalver** [ECP-copa/Cajita#2]
When configuring Cajita with a Kokkos installation, that was compiled with CUDA support,
and using g++ as C++ compiler, there seems to be a confusion about compilers:

```
[ 60%] Building CXX object src/CMakeFiles/Cajita.dir/Cajita_Block.cpp.o
g++: error: unrecognized command line option ‘-Xcudafe’
g++: error: unrecognized command line option ‘--diag_suppress=esa_on_defaulted_function_ignored’
g++: error: unrecognized command line option ‘-arch=sm_70’
g++: error: unrecognized command line option ‘-Xcompiler’; did you mean ‘--compile’?
```

Probably in this case the nvcc_wrapper from the Kokkos installation needs to be used?

**Comment by sslattery** [comment]
Yes! Here is how I configure with CUDA:

```

**Comment by sslattery** [comment]
Also make sure that the `NVCC_WRAPPER_DEFAULT_COMPILER` environment variable is set to your c++ compiler

**Comment by rhalver** [comment]
Thanks, that works for me in principle, if I pass "-w" as an CXX flag (removing all warnings). If I do not pass this flag, the following warning/error ends my compilation early:

```
[ 20%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
/home/halver/install/Cajita/build_cuda/googletest-src/googlemock/include/gmock/gmock-matchers.h:1775:17: error: unnecessary parentheses in declaration of ‘field_’ [-Werror=parentheses]
   const FieldType Class::*field_;
                 ^
cc1plus: all warnings being treated as errors
```

Is that some, that is too cautious due to my Kokkos installation, or can you reproduce that? I know, the origin of the warning / error is googletest, not the code itself.

**Comment by dalg24** [comment]
@rhalver Did you configure Kokkos to build with `-Werror`?

**Comment by rhalver** [comment]
Not that I could remember, I checked it and did not find -Werror, which is, what is confusing me about it. I basically used the Cabana building advice for building Kokkos with CUDA.

**Comment by sslattery** [comment]
Does `-Wall` add `-Werror`?

**Comment by dalg24** [comment]
> Does `-Wall` add `-Werror`?

No.

**Comment by rhalver** [comment]
Ok, I had a closer look at it and noticed, that -Werror is added from somewhere to the list of the compiler flags. The problem seems to be, that nvcc_wrapper throws for some reasons other warnings than g++. The case where the compilation stops with nvcc_wrapper throws no warning (and therefore no error) when using g++:

```
[ 20%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
cd /home/halver/install/Cajita/build_cuda/googletest-build/googlemock && /home/halver/kokkos/build/install/bin/nvcc_wrapper   -I/home/halver/install/Cajita/build_cuda/googletest-src/googlemock/include -I/home/halver/install/Cajita/build_cuda/googletest-src/googlemock -isystem /home/halver/install/Cajita/build_cuda/googletest-src/googletest/include -isystem /home/halver/install/Cajita/build_cuda/googletest-src/googletest  -Wall -Wextra -pedantic   -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++11 -o CMakeFiles/gmock.dir/src/gmock-all.cc.o -c /home/halver/install/Cajita/build_cuda/googletest-src/googlemock/src/gmock-all.cc
/home/halver/install/Cajita/build_cuda/googletest-src/googlemock/include/gmock/gmock-matchers.h:1775:17: error: unnecessary parentheses in declaration of ‘field_’ [-Werror=parentheses]
   const FieldType Class::*field_;
```

compared to:

```
[  5%] Building CXX object googletest-build/googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
cd /home/halver/install/Cajita/build/googletest-build/googlemock && /projects/opt/centos7/gcc/8.2.0/bin/g++   -I/home/halver/install/Cajita/build/googletest-src/googlemock/include -I/home/halver/install/Cajita/build/googletest-src/googlemock -isystem /home/halver/install/Cajita/build/googletest-src/googletest/include -isystem /home/halver/install/Cajita/build/googletest-src/googletest  -Wall -Wextra -pedantic   -Wall -Wshadow -Werror -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=c++11 -o CMakeFiles/gmock.dir/src/gmock-all.cc.o -c /home/halver/install/Cajita/build/googletest-src/googlemock/src/gmock-all.cc
[  7%] Linking CXX static library ../../lib/libgmock.a
```

A quick search indicated, that the -Wparanthesis warning might be overzealous in some gcc versions and I have no idea, with which gcc version the CUDA compiler was created, as it is not indicated in the module. So probably we can close this issue now, as the workaround for me is to pass "-w" to ignore the warning that leads to the error message, when using nvcc_wrapper.

**Comment by sslattery** [comment]
OK makes sense - and not surpassing that `nvcc` would emit other warnings that a new g++ does not. @rhalver if you are comfortable closing go ahead and we can reopen as needed
